// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://odolbpqrkwsrvecyhvvs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9kb2xicHFya3dzcnZlY3lodnZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0OTkzNzIsImV4cCI6MjA3MzA3NTM3Mn0.Eh_KLhCxC4vaRnqhoD6nrnzT9GVYsyoO7tKIgx27_Ps";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});